version: '3'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'jenkins_docker'
    restart: always
    user: jenkins
    ports:
      - '9080:8080'
      - '50020:50000'
    expose:
      - '8080'
      - '50000'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      TZ: "Asia/Seoul"
networks:
  default:
    external:
      name: devops

